[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["crates/coordinator_zomes/*", "crates/integrity_zomes/*"]


[workspace.dependencies]
hdi = "0.5.0-dev.2"
hdk = "0.4.0-dev.2"
serde = "1"
holochain = "0.4.0-dev.2"
